parameters: ['num_layers', 'dim_ff', 'num_heads', 'warmup_steps', 'epochs', 'dropout_rate']
num_layers: [2, 3]
dim_ff: [512]
num_heads: [1, 5, 10]
warmup_steps: [4000, 6000, 12000]
epochs: [45]
dropout_rate: [0.1]
