parameters: ['num_layers', 'dim_ff', 'num_heads', 'warmup_steps', 'epochs', 'dropout_rate']
num_layers: [2, 3, 4, 6]
dim_ff: [256, 512, 1024]
num_heads: [1, 5, 10]
warmup_steps: [100, 500, 4000]
epochs: [25]
dropout_rate: [0.1, 0.3]
