parameters: ['num_layers', 'dim_ff', 'num_heads', 'warmup_steps', 'epochs', 'dropout_rate', 'd_model']
num_layers: [2,3]
dim_ff: [512]
num_heads: [2,1,5]
warmup_steps: [4000]
epochs: [71]
dropout_rate: [0.1]
d_model: [100]
