parameters: ['num_layers', 'dim_ff', 'num_heads', 'warmup_steps', 'epochs', 'dropout_rate', 'd_model', 'seed']
num_layers: [3,4]
dim_ff: [256, 512]
num_heads: [2, 1]
warmup_steps: [4000]
epochs: [85]
dropout_rate: [0.1]
d_model: [50]
seed: [42]
